Updated GWeb examples
abahetik/webvi-examples pull request #2
Opened 2021-07-15 10:09 UTC by abahetik

# Justification
Replaced the LabVIEW webvi-examples with G Web Development Software examples

# Implementation
1. Replaced the LV Web module examples with the new G Web examples.
2. Retained the Readme files from the previous examples.
3. Replaced references of LabVIEW Web Module from .md files

2021-07-22 03:54 UTC, ansujay reviewed
We need to retain the CG project here: CallLabVIEWWebService/WebService/

Verify the CG project to make sure that it doesn't have any references (in comments, etc.) to NXG or Web Module. If it does, we should update to G Web Development Software.

2021-07-22 03:54 UTC, ansujay commented on Call3rdPartyWebService/.cache/paths.xml~RF1d320211.TMP
> +<SerializableDictionary>
We should not add these temp files.

2021-07-22 04:04 UTC, ansujay commented
See if you can have similar styling for all gifs. Most gifs in this repo are recorded on Chrome with light mode. The new gifs are on Edge (I think) and the dark mode is illegible to read. The toolbar should not show unnecessary icons.

2021-07-22 04:06 UTC, ansujay commented
The readme file under CustomizeWithCss folder needs to be updated to remove LabVIEW NXG Web Module reference.

2021-07-22 04:07 UTC, ansujay commented
The title in the readme under Guides/CSS should be updated. It currently reads Web Module Guides.

2021-07-22 04:11 UTC, ansujay commented
The "product documentation" link at the bottom of readme under Guides/Css points to Web Module.

2021-07-22 04:13 UTC, ansujay commented
>For questions related to topics discussed in the WebVI Example Guides, please ask in the LabVIEW NXG discussion forums.

The readme under Guides is pointing users to post under LabVIEW NXG discussion forums. I think Kiran asked that it should be LabVIEW forums.

2021-07-22 04:15 UTC, ansujay commented
>For previous LabVIEW NXG versions see the previous releases

In the main readme, we probably shouldn't say "previous" since LabVIEW NXG is a different product altogether.

2021-07-22 04:16 UTC, ansujay commented
>If you have any questions or general feedback about the examples please post in the LabVIEW NXG section of the LabVIEW Discussion Forums.

It is very odd to me that we would ask users to post under LabVIEW NXG. I think Kiran asked that we should be directing users to the LabVIEW forums, not NXG forums.

2021-07-22 04:19 UTC, ansujay commented
>This example uses the Web Module WebSockets API to connect to the WebSocket Echo Server hosted by https://websocket.org/.

In the main readme, we should remove the Web Module reference from above line.

2021-07-22 04:21 UTC, ansujay requested changes
I recommend loading the repo folder in VS Code and searching for LabVIEW NXG, Web Module, etc. to ensure that we don't missing updating any old product references.

Also look at all hyperlinks in the files (you can easily search for it by searching for "https://" or "http://" and make sure they are all correct.

2021-07-23 08:25 UTC, abahetik commented on Call3rdPartyWebService/.cache/paths.xml~RF1d320211.TMP
> +<SerializableDictionary>
Deleted file

2021-07-28 06:01 UTC, ansujay reviewed
The ConnectWebVIToWebSocketEchoServer/Readme.md file has link to Web Module documentation at the bottom.

2021-07-28 06:01 UTC, ansujay commented on CallLabVIEWWebService/Readme.md
> +- **`Web Service`** &mdash; Contains the G Web web service project.
This change is incorrect. The project under Web Service folder is a LabVIEW project, not a G Web project.

2021-07-28 06:01 UTC, ansujay commented on CallLabVIEWWebService/Readme.md
> +The web service is created in G Web Development Software and consists of two HTTP endpoint methods (one `GET` and one `POST`) and a few SubVIs.
Should be LabVIEW.

2021-07-28 06:01 UTC, ansujay commented on CallLabVIEWWebService/Readme.md
> +You must configure the Output Type correctly in order for a G Web web service to send data to a WebVI.
LabVIEW

2021-07-28 06:01 UTC, ansujay commented on CallLabVIEWWebService/Readme.md
> +**Note:** This option returns data through VI output terminals and serializes G Web data into JSON automatically.
LabVIEW

2021-07-28 06:01 UTC, ansujay commented on CallLabVIEWWebService/Readme.md
> +Cross-Origin Resource Sharing (CORS) allows a Web Service VI to respond to HTTP requests from a different server than where it is hosted. `AddCORSHeaders.vi` adds HTTP headers to allow requests from
LabVIEW

2021-07-28 06:01 UTC, ansujay commented on CallLabVIEWWebService/Readme.md
> +The `WebApp_Web Server` directory has been included as **Public Content** within the G Web project. This was done by right-clicking the Web service in the project and selecting Add **Public Content F
Incorrect G Web references, should be replaced by LabVIEW.

LabVIEW NXG, on the other hand, should be replaced by G Web Development Software.

2021-07-28 06:01 UTC, ansujay commented on CallLabVIEWWebService/Readme.md
> +- **Use Absolute URLs and Local Debugging**: This uses fully qualified URLs; e.g. `http://127.0.0.1:8001/Web_Server/ParametricCurve` in each HTTP request. Fully qualified URLs must be used if the Web
Leave LabVIEW as-is.

2021-07-28 06:01 UTC, ansujay commented on CallLabVIEWWebService/Readme.md
> +- **Use Relative URLs and Application Web Server**: This uses a relative URLs; e.g. `ParametricCurve` in each HTTP request. The rest of the URL is filled in automatically by the browser. This techniq
Leave LabVIEW as-is.

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
>  - LabVIEW NXG with [LabVIEW NXG Web Module](http://www.ni.com/labview/webmodule/)
Should we remove NXG and Web Module since they are discontinued?

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
>  - LabVIEW 2016-2019 with SystemLink Client 19.5
Add latest versions of LabVIEW as well.

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
> +![Configure GVI in G Web Development Software vs Hosting in SystemLink Cloud](readme_files/cloud-config.PNG)
This image still says LabVIEW NXG in it.

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
> +_Figure: Note the input differentiation between connecting to the SystemLink Cloud server from G Web Development Software vs. hosting your web application on SystemLink Cloud._
It should say "LabVIEW or G Web Development Software".

LabVIEW is not being discontinued, it's just LabVIEW NXG.

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
> +_Figure: Note the input differentiation between connecting to an  on-premises server from G Web Development Software vs. hosting your web application on the NI Web Server._
"LabVIEW or G Web Development Software"

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
> +![Configure GVI in G Web Development Software vs Hosting on premises](readme_files/on-premises-config.PNG)
The image still says LabVIEW NXG inside.

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
> +#### Hosting on the G Web Development Server
This change is incorrect.

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
> +1. Go to the G Web Development Software Web Server directory using the following path: `C:\Program Files (x86)\National Instruments\Shared\NI WebServer\www`.
This change is incorrect.

2021-07-28 06:01 UTC, ansujay commented on CallSystemLinkDataServices/Readme.md
> +2. Copy the entire `Full Data Services App_Web Server` directory into the `www` directory of the G Web Development Software web server.
This change is incorrect.

2021-07-28 06:01 UTC, ansujay commented on ConnectWebVIToWebSocketEchoServer/Readme.md
> +This example uses the G Web WebSockets API to connect to the WebSocket Echo Server hosted by https://websocket.org/. The WebVI connects to the server, sends a message, and receives the same message f
G Web Development Software

2021-08-06 07:46 UTC, ansujay approved these changes

2021-08-08 15:55 UTC, merged